version: '3.8'

services:

  batch:
    image: postgres:latest
    container_name: batch
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=cornel
      - POSTGRES_PASSWORD=sefusefu
      - POSTGRES_DB=batch

  input:
    image: postgres:latest
    container_name: input
    ports:
      - "5434:5432"
    environment:
      - POSTGRES_USER=cornel
      - POSTGRES_PASSWORD=sefusefu
      - POSTGRES_DB=input

  output:
    image: postgres:latest
    container_name: output
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=cornel
      - POSTGRES_PASSWORD=sefusefu
      - POSTGRES_DB=output